#!/bin/tcsh
echo "# script for preparing beta carotene molecules with rotating ionone rings as ligand pdbqt files "
set path_python = /Applications/Darwin/mgltools_i86Darwin9_1.5.6/bin
set path_utilities = /Applications/Darwin/mgltools_i86Darwin9_1.5.6/MGLToolsPckgs/AutoDockTools/Utilities24 
set path_ligand = /Users/Pappa/Docking/beta_carotene
foreach ligand_name ( `cat root_names_betacaroteneBCR` )
   echo -n "processing carotene "
   echo "$ligand_name"
   grep -v -f exclude $path_ligand/$ligand_name"_bcr.pdb" > temp_bcr 
   grep -f search temp_bcr | cut -c 1-6 > temp1 
   grep -f search temp_bcr | cut -c 12-78 > temp2
   paste -d '\' temp1 carotene-atomids.pdbqt temp2 > $ligand_name"_bcr5.pdb" 
   $path_python/pythonsh $path_utilities/prepare_ligand4.py -l $ligand_name"_bcr5.pdb" -A hydrogens -U nphs_lps -Z
   cat activate_torsionC6C7C26C27_bcr.vi | vi $ligand_name"_bcr5.pdbqt"
end
echo "# last line of the vina script - MPH 30-May-2019  - MPH 25-May-2021 - MPH 06-June-2021"
