#!/bin/tcsh
echo "# script for preparing lutein molecules as ligand pdbqt files "
set path_utilities = /Applications/Darwin/mgltools_i86Darwin9_1.5.6/MGLToolsPckgs/AutoDockTools/Utilities24 
set path_python = /Applications/Darwin/mgltools_i86Darwin9_1.5.6/bin
set path_ligand = /Users/Pappa/Docking/dietary_lutein
foreach ligand_name ( `cat root_names_luteinligand.csv` )
   echo -n "processing lutein "
   echo "$ligand_name"
   cp $ligand_name"_luteinligand.pdb" $ligand_name"_luteinligand_lut2.pdb" 
   cp $ligand_name"_luteinligand.pdb" $ligand_name"_luteinligand_lut5.pdb" 
   $path_python/pythonsh $path_utilities/prepare_ligand4.py -l $ligand_name"_luteinligand_lut2.pdb" -A hydrogens -U nphs_lps -Z
   $path_python/pythonsh $path_utilities/prepare_ligand4.py -l $ligand_name"_luteinligand_lut5.pdb" -A hydrogens -U nphs_lps -Z
   cat activate_torsionC6C7C26C27_lut.vi | vi $ligand_name"_luteinligand_lut5.pdbqt"
end
echo "# last line of the script - MPH 30-May-2019  - MPH 25-May-2021 - MPH 06-June-2021 - MPH 14-October-2021 - MPH 17-February-2022"
